# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "feature" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Below we need to temporarily disable
    #- name: Generate the Jacoco report
    #  run: mvn jacoco:report
    
    #- name: Generate JaCoCo Badge
    #  id: jacoco
    #  uses: cicirello/jacoco-badge-generator@v2.11.0
    #- name: Log coverage percentage
    #  run: |
    #    echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
    #    echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    
    #- name: Upload JaCoCo coverage report
     # uses: actions/upload-artifact@v4
     # with:
     #     name: jacoco-report
     #     path: target/site/jacoco/

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # Also needs to be disable due to failures in the current repository
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@v3

    - name: Upload mag artifact snapshot jar
      uses: actions/upload-artifact@v4
      with:
        name: mag-jar-simple--${{ github.sha }}
        path: target/mobile-access-gateway-1.0-SNAPSHOT.jar

    - name: Upload mag artifact snapshot spring-boot jar
      uses: actions/upload-artifact@v4
      with:
        name: mag-jar-Springboot--${{ github.sha }}
        path: target/mobile-access-gateway-1.0-SNAPSHOT-spring-boot.jar
